### ISSUE TITLE
Issues with running in unix with docker host running over unix socket

### ISSUE THREAD

**Issue by aniketbhatnagar** [getintent/embedded-aerospike#4]
I have noticed following issues when running this library in unix with docker host running over unix socket:
- javax.ws.rs.ProcessingException
  
  should be handled in AerospikeContainerMonitor as it seems to mysteriously crops up after the docker image has started and has no bearing on the running aerospike. 
  Full stack trace:

```
Caused by: javax.ws.rs.ProcessingException: Error closing message content input stream.
    at org.glassfish.jersey.message.internal.EntityInputStream.close(EntityInputStream.java:159)
    at org.glassfish.jersey.message.internal.InboundMessageContext$EntityContent.close(InboundMessageContext.java:151)
    at org.glassfish.jersey.message.internal.InboundMessageContext.close(InboundMessageContext.java:909)
    at com.github.dockerjava.jaxrs.connector.ApacheConnectorClientResponse.close(ApacheConnectorClientResponse.java:45)
    at org.glassfish.jersey.client.InboundJaxrsResponse.close(InboundJaxrsResponse.java:163)
    at com.github.dockerjava.jaxrs.util.WrappedResponseInputStream.close(WrappedResponseInputStream.java:57)
    at com.github.dockerjava.core.async.ResultCallbackTemplate.close(ResultCallbackTemplate.java:80)
    at com.getintent.aerospike.embedded.AerospikeContainerMonitor.run(AerospikeContainerMonitor.java:41)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: Bad file descriptor at Socket[addr=0.0.0.0/0.0.0.0,port=0,localport=0][fd=java.io.FileDescriptor@d178fb7; file=/var/run/docker.sock; connected=false; bound=false]
    at org.newsclub.net.unix.AFUNIXSocketImpl$AFUNIXInputStream.read(AFUNIXSocketImpl.java:190)
    at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:139)
    at org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:155)
    at org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:284)
    at org.apache.http.impl.io.ChunkedInputStream.getChunkSize(ChunkedInputStream.java:266)
    at org.apache.http.impl.io.ChunkedInputStream.nextChunk(ChunkedInputStream.java:227)
    at org.apache.http.impl.io.ChunkedInputStream.read(ChunkedInputStream.java:186)
    at org.apache.http.impl.io.ChunkedInputStream.read(ChunkedInputStream.java:215)
    at org.apache.http.impl.io.ChunkedInputStream.close(ChunkedInputStream.java:316)
    at org.apache.http.impl.execchain.ResponseEntityProxy.streamClosed(ResponseEntityProxy.java:140)
    at org.apache.http.conn.EofSensorInputStream.checkClose(EofSensorInputStream.java:228)
    at org.apache.http.conn.EofSensorInputStream.close(EofSensorInputStream.java:174)
    at java.io.BufferedInputStream.close(BufferedInputStream.java:483)
    at java.io.FilterInputStream.close(FilterInputStream.java:181)
    at com.github.dockerjava.jaxrs.connector.ApacheConnector$HttpClientResponseInputStream.close(ApacheConnector.java:610)
    at org.glassfish.jersey.message.internal.EntityInputStream.close(EntityInputStream.java:157)
    ... 12 common frames omitted
Caused by: org.newsclub.net.unix.AFUNIXSocketException: Bad file descriptor
    at org.newsclub.net.unix.NativeUnixSocket.read(Native Method)
    at org.newsclub.net.unix.AFUNIXSocketImpl$AFUNIXInputStream.read(AFUNIXSocketImpl.java:187)
    ... 27 common frames omitted

```
- Since the docker host is unix:///var/run/docker.sock, dockerConfig.getDockerHost().getHost() returns null. Therefore, in this case, host should default to localhost in getHostAndPort.

**Comment by maxkraynov** [comment]
Hi, @aniketbhatnagar! Thank you for your issue. I would like to draw your attention to the [testcontainers-java](https://github.com/testcontainers/testcontainers-java) project. Actually, it's full-featured test framework based on docker containers.
You easy can run aerospike with this snippet

``` java
public static GenericContainer aerosike =
            new GenericContainer("aerospike:latest")
                    .withExposedPorts(3000)
                    .withClasspathResourceMapping("aerospike.conf", "/etc/aerospike/aerospike.conf", BindMode.READ_ONLY);
```

We are going to close embedded-aerospike project and focus on contributing to **testcontainers-java** project.
